### ISSUE TITLE
Changed paths for agent_based v2 API plugins

### ISSUE THREAD

**Issue by bduff-fl** [jiuka/checkmk_template#5]
As I'm learning about the agent-based plugin v2 API, it looks like the `.devcontainer/` files do not map workspace directories to the needed paths for the API. Could that be updated? 

In a non-docker hosted site, I have my new plugin in this path:
`~/local/lib/python3/cmk_addons/plugins/my_new_plugin/agent_based/my_new_plugin.py`
I am unsure how to solve for the variable plugin folder name (`my_new_plugin`) that must exist in the path, so I don't know how to change the `symlink.sh` to accomplish this.

**Comment by jiuka** [comment]
There shoud be no need to change the symlink.sh as it read the path from the package file.

**Comment by bduff-fl** [comment]
I must be not understanding the symlink script or making some other error then. I couldn't get any agent_based.v2 code to work until I changed over to a remote explorer/remote ssh plugin pointing to a non-docker container running a dev 2.3 site. 

If you are confident this is an issue on my side I will close this then.
